# Welcome to Jekyll!

title: Muhamed Javid Hussain - Technical Writer Portfolio
email: javidwriter@gmail.com
description: >-
  Senior technical writer specializing in clear, user-friendly documentation.
  9 years of experience in transforming complex technical concepts into 
  accessible content that helps users achieve their goals.

baseurl: "/Technical-writer-portfolio" # the subpath of your site, matches repo name!
url: "https://muhamed-javid-writer.github.io" # your GitHub Pages base URL

github_username: Muhamed-javid-writer
linkedin_username: muhamed-javid

# Build settings
theme: minima
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections for organizing content
collections:
  user_guides:
    output: true
    permalink: /:collection/:name/
  developer_guides:
    output: true
    permalink: /:collection/:name/
  knowledge_base:
    output: true
    permalink: /:collection/:name/

# Navigation menu
header_pages:
  - about.md
  - resume.md
  - portfolio.md
  - testimonials.md
  - contact.md

author:
  name: Muhamed Javid Hussain
  email: javidwriter@gmail.com

minima:
  skin: auto
  social_links:
    github: Muhamed-javid-writer
    linkedin: muhamed-javid
    email: javidwriter@gmail.com

# Uncomment and set if you use Google Analytics
# google_analytics: UA-NNNNNNNN-N
